### ISSUE TITLE
Projectile Tallying f93fc31 Breaks projectile functionality

### ISSUE THREAD

**Issue by ghost** [ikemen-engine/Ikemen-GO#1512]
### Describe the bug

The commit f93fc31 seems to break functionality of when a projectile should be removed. The character in this example, Mothra (mothra_A) spawns a helper that then spawns a projectile every frame, the projectile is set to last only 1 frame then remove itself. There should be 2 instances of these each frame. The trigger that changes this helper into an "Explode" state, calculates when there is less then 2 of these numproj. Meaning, if something hits the projectile, it should remove atleast 1, therefore less than 2 and trigger the changestate.

This works in Mugen 1.1, 0.98, and 0.99 Stable. 

[EDITED Test Files Mugen 1.1.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13441653/EDITED.Test.Files.Mugen.1.1.zip)
[EDITED Ikemen GO 99.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13441658/EDITED.Ikemen.GO.99.zip)

### To Reproduce

Download zip attachments from above.

1. Open Test Files Mugen, do 1 v 1 of Mothra as P1 vs Mechagodzilla as P2
2. Press the keyboard key "C" for Mothra to launch the dust glitter projectile
3.  As mechagodzilla, press the "L" keyboard key to launch his projectile energy attack and aim at mothras dust glitter projectile
4. It should ignite (see video)
5. Open Ikemen GO 99 Folder, 
6. Test the same thing on Ikemen_GO_99_latest_Nov18.exe and it will not do anything
7. Test the same thing on Ikemen_GO_99_Stable.exe and it should work
8. Another test, just revert f93fc31, build, and test these 2 characters (I reverted this and it fixed the issue)

### Expected behavior

The dust projectile should change state into its explode state

### Screenshots / Video

https://github.com/ikemen-engine/Ikemen-GO/assets/68257059/d80e50e2-bd7e-488f-b774-475197e805f1

### Engine Version (or source code date)

v0.99 latest Nov 18th

### Operating system

Windows

### Extra context or search terms

projectile

**Comment by potsmugen** [comment]
This is pretty interesting because the move did work in Ikemen 0.98.2, but not the same way that it does in Mugen. In Mugen, what makes the cloud explode is the HitOverride (you can see with debug that it gets hit - time changes to -1) but in Ikemen it activates because one of the projectiles is removed, as you said. So Ikemen never actually reproduced the Mugen behavior of this move 100% it seems.

There are a number of ways to make the move work corectly in both engines from the character side, but yeah this is showing a difference between the engines that should be addressed. I'm just not yet sure how to address it without regressing the other characters that were fixed by that commit (and the one after it).

This issue seems multifaceted and may take a good while to sort out, so at the risk of sounding like a jerk I think you should refactor it in the meantime to account for engine changes.

**Comment by ghost** [comment]
Thanks for taking a look. Interesting find regarding the hitoverride. That was actually not supposed to be in there, so i removed it since it does not need it, but just thought I'd add the bug still happens without the hitoverride in place (and now .98 and mugen reproduce this the same method). I've added edited files that removes that override. This can also be hit by your partner, and it seems to also display the same issue when your partner tries to hit it as well (attached video)

And no worries about refactoring, ill probably remove this commit on my personal build since its a closed game and as far as i know, no character on my roster is affected by the initial reported bug that caused this commit to take place (either that or I unknowingly worked around it)

[EDITED Test Files Mugen 1.1.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13441653/EDITED.Test.Files.Mugen.1.1.zip)
[EDITED Ikemen GO 99.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13441658/EDITED.Ikemen.GO.99.zip)


https://github.com/ikemen-engine/Ikemen-GO/assets/68257059/6193e1e8-5264-4e12-bd97-a904ae680e10

**Comment by updeshxp** [comment]
@potsmugen I think this is the same issue which I am seeing in Nightly version only, works fine in 0.99 stable and earlier versions:

0.99 and MUGEN 1.1b (Works as expected)

https://github.com/ikemen-engine/Ikemen-GO/assets/17386732/988ab5a8-3476-4b95-b71f-634dfb9fe391

Latest Nightly as of 15-Jan-2024:

https://github.com/ikemen-engine/Ikemen-GO/assets/17386732/0a41910e-c512-4f54-840e-046dcf177dd4

Here's the char if needed:

[Remy.zip](https://github.com/ikemen-engine/Ikemen-GO/files/13933039/Remy.zip)

**Comment by potsmugen** [comment]
Think I found a way to fix this one without regressing the other issues that were fixed. I'll PR it later after more testing.
